name: Update World Index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run index generator
        run: |
          python scripts/update_world_index.py

      - name: Commit changes (if any)
        run: |
          git config user.name "hopefulvision-bot"
          git config user.email "bot@hopefulvision.llc"
          git add HopefulVision_World_Index_AUTO.md
          git commit -m "🤖 Auto-update world index" || echo "No changes to commit"
          git push
