name: Update World Index

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-world-index
  cancel-in-progress: true

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v4

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run index generator
        run: python scripts/update_world_index.py

      - name: Commit generated index (if changed)
        run: |
          git config user.name "hopefulvision-bot"
          git config user.email "bot@hopefulvision.llc"
          git add HopefulVision_World_Index_AUTO.md
          git commit -m "🤖 Auto-update world index" || echo "No changes to commit"
          git push
